### ISSUE TITLE
Alois Type erasure

### ISSUE THREAD

**Issue by maddanio** [beark/ftl#20]
Hi, maybe this rant is premature, but I was skimming through the library and found it uses type erasure for functions. I was wondering why this is necessary, and why not the full type can be preserved to avoid tHe indirection and allow complete inlining. I am using functional techniques for code that runs at about 1mio operations/s, so the use of type erasure does not seem an option for me and may make it impossible for me to use ftl.

**Comment by beark** [comment]
It's necessary to preserve function signatures in some cases. Given some function-like type `F`, there's no way of figuring out which argument type(s) it expects. However, given a `function<B(A)>`, we know it expects an `A` and returns a `B`.

I'm aware of the cost of this, though, and have tried to make sure that in every case where the function signature is not needed, the library accepts a template function type instead, eg

    template<typename F, typename U = result_of<F(T)>>
    static constexpr maybe<U> map(F f, maybe<T>&& m) {
        return m.match(
            [f](T& t){ return just(f(std::move(t))); },
            [](Nothing){ return Nothing{}; }
        );
    }

Though honestly, all of the above is kind of moot, because I can't at this point recommend anyone to use the FTL. I haven't really kept up maintenance or development in over a year. For example, using C++14 features, the above could have forwarded `f` into the closure instead of always copying it.

**Comment by maddanio** [comment]
Boost has some utilities to infer sigbatures I think. So maybe I will try forking some time :). First have to learn Haskell though. Just started with "real world Haskell", good read :)
